// Playbook-first ISL synonyms. Keys are lowercase English or Hindi.
// Values are catalog lemmas that MUST exist as .sigml files (enforced in tests).
// One sign, many clerk phrasings — never invent a new sign.

/** Longer phrases first. Replaced with catalog lemmas. */
export const PHRASES: Array<[string, string[]]> = [
  ["i did not understand", ["donotunderstand"]],
  ["i didn't understand", ["donotunderstand"]],
  ["did not understand", ["donotunderstand"]],
  ["do not understand", ["donotunderstand"]],
  ["don't understand", ["donotunderstand"]],
  ["not understand", ["donotunderstand"]],
  ["समझ नहीं आया", ["donotunderstand"]],
  ["समझ नहीं आ रहा", ["donotunderstand"]],
  ["समझ नहीं", ["donotunderstand"]],
  ["i understand", ["iunderstand"]],
  ["i understood", ["iunderstand"]],
  ["please repeat", ["repeat"]],
  ["say again", ["repeat"]],
  ["speak slowly", ["slow"]],
  ["please hold the line", ["hold", "wait"]],
  ["hold the line", ["hold", "wait"]],
  ["please hold", ["hold", "wait"]],
  ["hold on", ["hold", "wait"]],
  ["कृपया प्रतीक्षा", ["wait"]],
  ["एक मिनट रुकिए", ["wait"]],
  ["power has been out", ["power", "cut"]],
  ["power is out", ["power", "cut"]],
  ["power been out", ["power", "cut"]],
  ["power out", ["power", "cut"]],
  ["power cut", ["power", "cut"]],
  ["load shedding", ["power", "cut"]],
  ["loadshedding", ["power", "cut"]],
  ["no electricity", ["electricity", "none"]],
  ["बिजली गुल", ["power", "cut"]],
  ["बिजली कटौती", ["power", "cut"]],
  ["बिजली नहीं", ["electricity", "none"]],
  ["complaint number", ["complaint", "number"]],
  ["ticket number", ["ticket", "number"]],
  ["reference number", ["ticket", "number"]],
  ["registration number", ["form", "number"]],
  ["consumer number", ["number"]],
  ["account number", ["number"]],
  ["card number", ["number"]],
  ["शिकायत संख्या", ["complaint", "number"]],
  ["शिकायत नंबर", ["complaint", "number"]],
  ["what is your name", ["yournamewhat"]],
  ["your name", ["name"]],
  ["thank you for calling", ["thankyou"]],
  ["thank you", ["thankyou"]],
  ["book an appointment", ["appointment"]],
  ["book appointment", ["appointment"]],
  ["no beds", ["clinic", "none"]],
  ["beds available", ["available"]],
  ["not available", ["available", "none"]],
  ["please wait", ["wait"]],
  ["call back", ["call", "later"]],
  ["come today", ["come", "today"]],
  ["visit today", ["visit", "today"]],
  ["help me", ["help-me"]],
  ["help you", ["help-you"]],
  ["give me", ["give-me"]],
  ["ask a question", ["askquestion"]],
  ["do not share otp", ["none"]],
  ["don't share otp", ["none"]],
  ["block the card", ["avoid", "money"]],
  ["block card", ["avoid", "money"]],
  ["unauthorized transaction", ["money", "problem"]],
  ["cyber crime", ["problem", "officer"]],
  ["last four digits", ["number"]],
  ["engineer will visit", ["engineer", "visit"]],
  ["electrician will", ["electrician"]],
  ["line is down", ["line", "problem"]],
  ["heart problem", ["heartbeat", "problem"]],
  ["please come", ["come"]],
  ["i will check", ["check"]],
  ["we will send", ["send"]],
];

export const WORD_SYNONYMS: Record<string, string[]> = {
  // Power cut
  electricity: ["electricity"],
  power: ["power"],
  outage: ["power", "cut"],
  blackout: ["power", "cut"],
  loadshedding: ["power", "cut"],
  "load-shedding": ["power", "cut"],
  cut: ["cut"],
  गुल: ["cut"],
  कटौती: ["cut"],
  बिजली: ["electricity"],
  transformer: ["wire"],
  fuse: ["wire"],
  cable: ["wire"],
  meter: ["electricity"],
  electrician: ["electrician"],
  engineer: ["engineer"],
  technician: ["engineer"],
  line: ["line"],
  wire: ["wire"],
  area: ["area"],
  colony: ["area"],
  locality: ["area"],
  address: ["area"],
  क्षेत्र: ["area"],
  कॉलोनी: ["area"],
  complaint: ["complaint"],
  शिकायत: ["complaint"],
  ticket: ["ticket"],
  reference: ["ticket"],
  registration: ["form"],
  registering: ["form"],
  registered: ["form"],
  संदर्भ: ["ticket"],
  पंजीकरण: ["form"],
  consumer: ["number"],
  customer: ["name"],

  // Always-present call phrases
  wait: ["wait"],
  hold: ["hold"],
  repeat: ["repeat"],
  again: ["repeat"],
  understand: ["understand"],
  slowly: ["slow"],
  slow: ["slow"],
  please: ["please"],
  कृपया: ["please"],
  इंतजार: ["wait"],
  इंतज़ार: ["wait"],
  रुकिए: ["wait"],
  रुकें: ["wait"],
  दोहराइए: ["repeat"],
  दोहराएं: ["repeat"],
  दोहराएँ: ["repeat"],

  // Bank / 1930
  bank: ["money"],
  money: ["money"],
  amount: ["money"],
  rupees: ["money"],
  paid: ["pay"],
  payment: ["pay"],
  pay: ["pay"],
  refund: ["pay"],
  debit: ["money"],
  credit: ["money"],
  atm: ["money"],
  card: ["money"],
  account: ["number"],
  transaction: ["money"],
  fraud: ["problem"],
  scam: ["problem"],
  stolen: ["problem"],
  theft: ["problem"],
  cyber: ["problem"],
  block: ["avoid"],
  blocked: ["avoid"],
  police: ["officer"],
  officer: ["officer"],
  office: ["office"],
  बैंक: ["money"],
  पैसा: ["money"],
  रुपये: ["money"],
  खाता: ["number"],
  कार्ड: ["money"],
  धोखाधड़ी: ["problem"],
  धोखा: ["problem"],

  // Hospital
  hospital: ["clinic"],
  clinic: ["clinic"],
  doctor: ["doctor"],
  nurse: ["nurse"],
  ambulance: ["ambulance"],
  emergency: ["ambulance"],
  appointment: ["appointment"],
  patient: ["name"],
  bed: ["clinic"],
  ward: ["clinic"],
  fever: ["thermometer"],
  pain: ["health"],
  medicine: ["injection"],
  injection: ["injection"],
  blood: ["health"],
  heart: ["heartbeat"],
  operation: ["operation"],
  surgery: ["operation"],
  accident: ["accident"],
  bandage: ["bandage"],
  health: ["health"],
  lab: ["laboratory"],
  laboratory: ["laboratory"],
  test: ["laboratory"],
  scan: ["laboratory"],
  xray: ["laboratory"],
  "x-ray": ["laboratory"],
  admit: ["clinic", "come"],
  discharge: ["clinic", "go"],
  full: ["none"],
  slot: ["appointment"],
  अस्पताल: ["clinic"],
  डॉक्टर: ["doctor"],
  नर्स: ["nurse"],
  एम्बुलेंस: ["ambulance"],
  एम्बुलैंस: ["ambulance"],
  आपातकाल: ["ambulance"],
  मरीज: ["name"],
  अपॉइंटमेंट: ["appointment"],
  बुखार: ["thermometer"],
  दर्द: ["health"],
  दिल: ["heartbeat"],
  दुर्घटना: ["accident"],
  ऑपरेशन: ["operation"],

  // Shared call words
  number: ["number"],
  nomer: ["number"],
  नंबर: ["number"],
  संख्या: ["number"],
  name: ["name"],
  नाम: ["name"],
  phone: ["phone"],
  mobile: ["phone"],
  फोन: ["phone"],
  मोबाइल: ["phone"],
  call: ["call"],
  hello: ["hello"],
  yes: ["yes"],
  no: ["no"],
  not: ["none"],
  none: ["none"],
  empty: ["empty"],
  नहीं: ["none"],
  problem: ["problem"],
  issue: ["problem"],
  समस्या: ["problem"],
  sorry: ["sorry"],
  thanks: ["thankyou"],
  thank: ["thankyou"],
  thankyou: ["thankyou"],
  धन्यवाद: ["thankyou"],
  welcome: ["welcome"],
  today: ["today"],
  tomorrow: ["tomorrow"],
  yesterday: ["yesterday"],
  morning: ["morning"],
  evening: ["evening"],
  afternoon: ["afternoon"],
  night: ["night"],
  tonight: ["night"],
  now: ["now"],
  later: ["later"],
  time: ["time"],
  date: ["date"],
  day: ["day"],
  hour: ["time"],
  hours: ["time"],
  minute: ["time"],
  minutes: ["time"],
  week: ["day"],
  month: ["1month"],
  year: ["2months"],
  happened: ["when"],
  happen: ["when"],
  आज: ["today"],
  कल: ["tomorrow"],
  सुबह: ["morning"],
  शाम: ["evening"],
  रात: ["night"],
  दोपहर: ["afternoon"],
  come: ["come"],
  visit: ["visit"],
  go: ["go"],
  home: ["home"],
  work: ["work"],
  sent: ["send"],
  report: ["informus"],
  given: ["give-me"],
  receive: ["receive"],
  give: ["give-me"],
  take: ["take"],
  check: ["check"],
  confirm: ["correct"],
  ok: ["yes"],
  okay: ["yes"],
  right: ["correct"],
  correct: ["correct"],
  wrong: ["wrong"],
  done: ["finish"],
  finish: ["finish"],
  complete: ["finish"],
  need: ["need"],
  want: ["want"],
  help: ["help-me"],
  tell: ["informus"],
  ask: ["askquestion"],
  inform: ["informus"],
  details: ["detail"],
  detail: ["detail"],
  information: ["informus"],
  form: ["form"],
  fill: ["fill-in"],
  copy: ["copy"],
  save: ["save"],
  keep: ["keep"],
  look: ["havealook"],
  tools: ["tools"],
  repair: ["tools"],
  fix: ["tools"],
  available: ["available"],
  transfer: ["send"],
  transferred: ["send"],
  pending: ["wait"],
  resolved: ["finish"],
  know: ["know"],
  cannot: ["cannot"],
  can: ["can"],
  will: ["will"],
  what: ["what"],
  where: ["where"],
  who: ["who"],
  why: ["why"],
  how: ["how"],
  howmuch: ["howmuch"],
  "how-much": ["howmuch"],
  more: ["more"],
  less: ["less"],
  all: ["all"],
  any: ["any"],
  before: ["before"],
  after: ["after"],
  lateron: ["later"],
  soon: ["later"],
  since: ["time"],
  long: ["time"],
  until: ["time"],
  which: ["what"],
  note: ["keep"],
  नोट: ["keep"],
};

export const DROP_WORDS = new Set([
  "a",
  "an",
  "the",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "am",
  "to",
  "of",
  "for",
  "in",
  "at",
  "on",
  "it",
  "its",
  "it's",
  "im",
  "i'm",
  "has",
  "had",
  "have",
  "do",
  "does",
  "did",
  "would",
  "could",
  "should",
  "shall",
  "must",
  "might",
  "just",
  "very",
  "really",
  "also",
  "so",
  "if",
  "but",
  "and",
  "or",
  "from",
  "than",
  "then",
  "about",
  "into",
  "over",
  "under",
  "already",
  "still",
  "even",
  "only",
  "out",
  "off",
  "with",
  "without",
  "there",
  "here",
  "until",
  "which",
  "an",
  "we",
  "they",
  "i",
  "you",
  "he",
  "she",
  "me",
  "us",
  "him",
  "her",
  "my",
  "your",
  "our",
  "their",
  "his",
  "this",
  "that",
  "otp",
  "pin",
  "cvv",
  "password",
  "ओटीपी",
  "पिन",
  "पासवर्ड",
  "hai",
  "hain",
  "ka",
  "ki",
  "ke",
  "ko",
  "se",
  "mein",
  "me",
  "aap",
  "aapki",
  "aapka",
  "mera",
  "meri",
  "hum",
  "kya",
  "hai?",
]);

// "please" is a real catalog sign used on the call screen — keep it.
DROP_WORDS.delete("please");
